# version format
version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python36-x64"
  FBXSDK_SDKS: sdk

stack: python %PYTHON%

cache:
  - C:\Users\appveyor\.conan\data -> appveyor.yml

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: python --version
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan --version

build_script:
  - cmd: conan install . -i build -s build_type=Release -s compiler="Visual Studio" -s compiler.version=15
  - cmd: conan build -bf build .
  - cmd: move build\Release\FBX2glTF.exe build\Release\FBX2glTF-windows-x64.exe

test: off

artifacts:
  - path: build/Release/FBX2glTF-windows-x64.exe

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: OSvhQP0O9uaH+OFOJpbGiiBMRTOJ+H/VJHqVBhq39RNDnOfUEr/yjJNKh3JSdNqj
  artifact: build/Release/FBX2glTF-windows-x64.exe
  draft: true
  prerelease: true
  on:
#    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
